name: gita_ai
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  rename_app: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter_native_splash:
  image: assets/images/app_logo.png
  color: "#FFFFFF"

fonts:
  # Primary font for English
  - family: Poppins
    fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    
  # For Hindi/Sanskrit (Devanagari script)
  - family: NotoSansDevanagari
    fonts:
        - asset: fonts/NotoSansDevanagari-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansDevanagari-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansDevanagari-Bold.ttf
          weight: 700
    
  # For Tamil script
  - family: NotoSansTamil
    fonts:
        - asset: fonts/NotoSansTamil-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansTamil-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansTamil-Bold.ttf
          weight: 700
    
    # Optional: Serif font for quotes/emphasis
  - family: Crimson
    fonts:
        - asset: fonts/CrimsonText-Regular.ttf
          weight: 400
        - asset: fonts/CrimsonText-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/CrimsonText-SemiBold.ttf
          weight: 600  

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/images/splash_logo.png
