name: gita_ai
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  rename_app: ^1.6.5
  shared_preferences: ^2.2.2  # For storing user data locally
  share_plus: ^7.2.1
  audioplayers: ^5.2.1
  url_launcher: ^6.2.1
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter_native_splash:
  image: assets/images/app_logo.png
  color: "#FFFFFF"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/app_logo.png
    - assets/images/splash_logo.png
    - assets/icons/google_logo.png
    - assets/audios/gita_path_app.mp3
    - assets/images/tanpura.png
    - assets/images/chapters/
    - assets/images/social_logos/
  
  fonts:
    # Primary font for English
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    
    # For Hindi/Sanskrit (Devanagari script)
    - family: NotoSansDevanagari
      fonts:
        - asset: fonts/NotoSansDevanagari-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansDevanagari-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansDevanagari-Bold.ttf
          weight: 700
    - family: NotoSerifDevanagari
      fonts:
        - asset: fonts/NotoSerifDevanagari-Bold.ttf
          weight: 700
        - asset: fonts/NotoSerifDevanagari-SemiBold.ttf
          weight: 600
        - asset: fonts/NotoSerifDevanagari-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansDevanagari-Medium.ttf
          weight: 500

    
    # For Tamil script
    - family: NotoSansTamil
      fonts:
        - asset: fonts/NotoSansTamil-Medium.ttf
          weight: 400
        - asset: fonts/NotoSansTamil-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansTamil-Bold.ttf
          weight: 700
    
    # Optional: Serif font for quotes/emphasis
    - family: Crimson
      fonts:
        - asset: fonts/CrimsonText-Regular.ttf
          weight: 400
        - asset: fonts/CrimsonText-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/CrimsonText-SemiBold.ttf
          weight: 600